server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;


    # ==========================================
    # USER SERVICE PAGES
    # ==========================================

    location = /login.html {
        proxy_pass http://user-service:5001/login.html;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location = /register.html {
        proxy_pass http://user-service:5001/register.html;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # ==========================================
    # USER SERVICE JAVASCRIPT
    # ==========================================

    location = /js/login.js {
        proxy_pass http://user-service:5001/js/login.js;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location = /js/register.js {
        proxy_pass http://user-service:5001/js/register.js;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    
    location = /css/user-style.css {

    proxy_pass http://user-service:5001/css/user-style.css;

    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}


    # ==========================================
    # USER SERVICE API
    # ==========================================

    location /api/auth/ {

        proxy_pass http://user-service:5001/api/auth/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # ==========================================
    # PRODUCT SERVICE API
    # ==========================================

    location /api/products {

        proxy_pass http://product-service:5002/api/products;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # ==========================================
    # PRODUCT FRONTEND
    # ==========================================

    location / {

        try_files $uri $uri/ /index.html;
    }
}